[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "soundcloud-ma-provider"
dynamic = ["version"]
description = "SoundCloud provider for Music Assistant via nuvem_de_som"
requires-python = ">=3.12"
license = "Apache-2.0"
license-files = ["LICENSE"]
dependencies = ["music-assistant-plugin-manager", "music-assistant-models>=1.1.206", "nuvem_de_som"]

[project.optional-dependencies]
test = ["pytest", "pytest-asyncio"]

[project.entry-points."music_assistant.provider"]
soundcloud_free = "soundcloud_ma_provider"

[tool.setuptools.dynamic]
version = { attr = "soundcloud_ma_provider.version.__version__" }

[tool.setuptools.packages.find]
include = ["soundcloud_ma_provider*"]

[tool.setuptools.package-data]
soundcloud_ma_provider = ["manifest.json"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
